minimum_pre_commit_version: 2.13.0

default_language_version:
    python: python3.12


repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        description: Run black code format check for the codebase
        entry: black ./
        language: python
        types: ["python"]