networks:
  default:
    name: not-only-poke-bot-dev

services:
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 10s   # how often to check
      timeout: 5s     # the time after which check is considered failed
      retries: 5      # how many retries before considering Redis unhealthy
      start_period: 5s # how long to wait before starting the first check

  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '5540:5540'
    volumes:
      - ./data/redisinsight:/db
